project_id = "wrjqevcpxkfvfudbmdhp"

[functions.analyze-brand]
verify_jwt = false

[functions.discover-competitors]
verify_jwt = false

[functions.analyze-competitor]
verify_jwt = false

[functions.realtime-monitoring]
verify_jwt = false